# Generated by Django 3.2.6 on 2022-05-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=250)),
                ('i', models.ImageField(upload_to='x')),
                ('d', models.TextField()),
                ('r', models.IntegerField()),
            ],
        ),
    ]
